name: CI with Gradle

on:
  pull_request:
    branches: [ "develop", "release", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build jacocoTestReport

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: JaCoCo Code Coverage Summary
        uses: cicirello/jacoco-badge-generator@v2
        if: success() || failure()
        with:
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          generate-workflow-summary: true
          workflow-summary-heading: "📊 Code Coverage Summary"
